{{/*
PQC-FHE Kubernetes Secret Template
====================================
Stores sensitive configuration and credentials.

IMPORTANT SECURITY NOTES:
1. In production, use external secret management (Vault, AWS Secrets Manager, etc.)
2. Enable encryption at rest for etcd
3. Rotate secrets regularly
4. Use RBAC to restrict access

Reference:
- Kubernetes Secrets Best Practices
- NIST SP 800-57: Key Management
*/}}

{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pqc-fhe.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pqc-fhe.labels" . | nindent 4 }}
  annotations:
    # Prevent accidental deletion
    helm.sh/resource-policy: keep
    # Mark as sensitive
    kubernetes.io/description: "Contains sensitive PQC-FHE credentials"
type: Opaque
{{- if .Values.secrets.stringData }}
stringData:
  {{- range $key, $value := .Values.secrets.stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
data:
  # API authentication secret
  {{- if .Values.secrets.apiSecretKey }}
  API_SECRET_KEY: {{ .Values.secrets.apiSecretKey | b64enc }}
  {{- else }}
  # Auto-generated if not provided (32 bytes, base64 encoded)
  API_SECRET_KEY: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
  
  # JWT signing key for API tokens
  {{- if .Values.secrets.jwtSecretKey }}
  JWT_SECRET_KEY: {{ .Values.secrets.jwtSecretKey | b64enc }}
  {{- else }}
  JWT_SECRET_KEY: {{ randAlphaNum 64 | b64enc }}
  {{- end }}
  
  # Encryption key for key storage (AES-256)
  {{- if .Values.secrets.storageEncryptionKey }}
  STORAGE_ENCRYPTION_KEY: {{ .Values.secrets.storageEncryptionKey | b64enc }}
  {{- else }}
  STORAGE_ENCRYPTION_KEY: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
  
  # Redis password (if Redis auth is enabled)
  {{- if and .Values.redis.enabled .Values.redis.auth.enabled }}
  {{- if .Values.redis.auth.password }}
  REDIS_PASSWORD: {{ .Values.redis.auth.password | b64enc }}
  {{- else }}
  REDIS_PASSWORD: {{ randAlphaNum 24 | b64enc }}
  {{- end }}
  {{- end }}
  
  # Database connection string (if external DB is used)
  {{- if .Values.secrets.databaseUrl }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl | b64enc }}
  {{- end }}
  
  # External service credentials
  {{- if .Values.secrets.externalServices }}
  {{- range $name, $cred := .Values.secrets.externalServices }}
  {{ $name | upper }}_API_KEY: {{ $cred.apiKey | b64enc }}
  {{- if $cred.apiSecret }}
  {{ $name | upper }}_API_SECRET: {{ $cred.apiSecret | b64enc }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}

{{- if .Values.secrets.tls.enabled }}
---
# TLS Certificate Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pqc-fhe.fullname" . }}-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pqc-fhe.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  {{- if and .Values.secrets.tls.cert .Values.secrets.tls.key }}
  tls.crt: {{ .Values.secrets.tls.cert | b64enc }}
  tls.key: {{ .Values.secrets.tls.key | b64enc }}
  {{- if .Values.secrets.tls.ca }}
  ca.crt: {{ .Values.secrets.tls.ca | b64enc }}
  {{- end }}
  {{- else }}
  # Placeholder - replace with actual certificates
  tls.crt: ""
  tls.key: ""
  {{- end }}
{{- end }}

{{- if .Values.secrets.pqcKeys.enabled }}
---
# PQC Key Material Secret
# WARNING: In production, use external key management (HSM, Vault)
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pqc-fhe.fullname" . }}-pqc-keys
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pqc-fhe.labels" . | nindent 4 }}
  annotations:
    # Critical security resource
    kubernetes.io/description: "PQC cryptographic key material - HIGHLY SENSITIVE"
    helm.sh/resource-policy: keep
type: Opaque
data:
  # Master key encryption key (KEK) for wrapping PQC keys
  {{- if .Values.secrets.pqcKeys.masterKek }}
  MASTER_KEK: {{ .Values.secrets.pqcKeys.masterKek | b64enc }}
  {{- else }}
  # Auto-generated 256-bit KEK
  MASTER_KEK: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
  
  # Key derivation salt
  {{- if .Values.secrets.pqcKeys.kdSalt }}
  KD_SALT: {{ .Values.secrets.pqcKeys.kdSalt | b64enc }}
  {{- else }}
  KD_SALT: {{ randAlphaNum 16 | b64enc }}
  {{- end }}
{{- end }}

{{- if .Values.secrets.dockerRegistry.enabled }}
---
# Docker Registry Secret (for private images)
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pqc-fhe.fullname" . }}-registry
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pqc-fhe.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "pqc-fhe.dockerconfigjson" . }}
{{- end }}

{{- define "pqc-fhe.dockerconfigjson" -}}
{{- $registry := .Values.secrets.dockerRegistry.server -}}
{{- $username := .Values.secrets.dockerRegistry.username -}}
{{- $password := .Values.secrets.dockerRegistry.password -}}
{{- $email := .Values.secrets.dockerRegistry.email | default "" -}}
{{- $auth := printf "%s:%s" $username $password | b64enc -}}
{{- printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" $registry $username $password $email $auth | b64enc -}}
{{- end -}}

{{- if .Values.secrets.externalSecretOperator.enabled }}
---
# External Secrets Operator - ClusterSecretStore reference
# Use this when integrating with Vault, AWS Secrets Manager, etc.
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "pqc-fhe.fullname" . }}-external
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pqc-fhe.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secrets.externalSecretOperator.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.secrets.externalSecretOperator.secretStoreName }}
    kind: {{ .Values.secrets.externalSecretOperator.secretStoreKind | default "ClusterSecretStore" }}
  target:
    name: {{ include "pqc-fhe.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    {{- range .Values.secrets.externalSecretOperator.keys }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteKey }}
        {{- if .property }}
        property: {{ .property }}
        {{- end }}
    {{- end }}
{{- end }}
